---
version: 2
sources:
- name: "avpreet_random_prophecy_io_team.dummy"
  database: "avpreet_random_prophecy_io_team"
  schema: "dummy"
  tables:
  - name: "rides"
    columns:
    - name: "ride_id"
      dataType:
        type: "BigInt"
    - name: "customer_id"
      dataType:
        type: "BigInt"
    - name: "ride_date"
      dataType:
        type: "Date"
    - name: "fare_amount"
      dataType:
        type: "Double"
    type: "table"
  - name: "uber_data"
    columns:
    - name: "Date"
      dataType:
        type: "Date"
    - name: "Time"
      dataType:
        type: "Time"
    - name: "Booking ID"
      dataType:
        type: "String"
    - name: "Booking Status"
      dataType:
        type: "String"
    - name: "Customer ID"
      dataType:
        type: "String"
    - name: "Vehicle Type"
      dataType:
        type: "String"
    - name: "Pickup Location"
      dataType:
        type: "String"
    - name: "Drop Location"
      dataType:
        type: "String"
    - name: "Avg VTAT"
      dataType:
        type: "String"
    - name: "Avg CTAT"
      dataType:
        type: "String"
    - name: "Cancelled Rides by Customer"
      dataType:
        type: "String"
    - name: "Reason for cancelling by Customer"
      dataType:
        type: "String"
    - name: "Cancelled Rides by Driver"
      dataType:
        type: "String"
    - name: "Driver Cancellation Reason"
      dataType:
        type: "String"
    - name: "Incomplete Rides"
      dataType:
        type: "String"
    - name: "Incomplete Rides Reason"
      dataType:
        type: "String"
    - name: "Booking Value"
      dataType:
        type: "String"
    - name: "Ride Distance"
      dataType:
        type: "String"
    - name: "Driver Ratings"
      dataType:
        type: "String"
    - name: "Customer Rating"
      dataType:
        type: "String"
    - name: "Payment Method"
      dataType:
        type: "String"
    type: "table"
