---
version: 2
sources:
- name: "avpreet_random_prophecy_io_team.dummy"
  database: "avpreet_random_prophecy_io_team"
  schema: "dummy"
  tables:
  - name: "crocs"
    columns:
    - name: "Observation ID"
      dataType:
        type: "BigInt"
    - name: "Common Name"
      dataType:
        type: "String"
    - name: "Scientific Name"
      dataType:
        type: "String"
    - name: "Family"
      dataType:
        type: "String"
    - name: "Genus"
      dataType:
        type: "String"
    - name: "Observed Length (m)"
      dataType:
        type: "Double"
    - name: "Observed Weight (kg)"
      dataType:
        type: "Double"
    - name: "Age Class"
      dataType:
        type: "String"
    - name: "Sex"
      dataType:
        type: "String"
    - name: "Date of Observation"
      dataType:
        type: "String"
    - name: "Country/Region"
      dataType:
        type: "String"
    - name: "Habitat Type"
      dataType:
        type: "String"
    - name: "Conservation Status"
      dataType:
        type: "String"
    - name: "Observer Name"
      dataType:
        type: "String"
    - name: "Notes"
      dataType:
        type: "String"
    type: "table"
  - name: "support_tickets"
    columns:
    - name: "ticket_id"
      dataType:
        type: "BigInt"
    - name: "customer_id"
      dataType:
        type: "BigInt"
    - name: "issue_type"
      dataType:
        type: "String"
    type: "table"
  - name: "xlxs_file"
    columns:
    - name: "ID"
      dataType:
        type: "BigInt"
    - name: "Name"
      dataType:
        type: "String"
    - name: "About"
      dataType:
        type: "String"
    - name: "Age"
      dataType:
        type: "BigInt"
    - name: "Salary"
      dataType:
        type: "Double"
    - name: "JoinDate"
      dataType:
        type: "String"
    - name: "Email"
      dataType:
        type: "String"
    - name: "Address"
      dataType:
        type: "String"
    - name: "RelationIds"
      dataType:
        type: "String"
    - name: "IP"
      dataType:
        type: "String"
    - name: "Comments"
      dataType:
        type: "String"
    - name: "Phone"
      dataType:
        type: "String"
    - name: "Feedback"
      dataType:
        type: "String"
    - name: "Category"
      dataType:
        type: "String"
    type: "table"
  - name: "rides"
    columns:
    - name: "ride_id"
      dataType:
        type: "BigInt"
    - name: "customer_id"
      dataType:
        type: "BigInt"
    - name: "ride_date"
      dataType:
        type: "Date"
    - name: "fare_amount"
      dataType:
        type: "Double"
    type: "table"
  - name: "uber_data"
    columns:
    - name: "Date"
      dataType:
        type: "Date"
    - name: "Time"
      dataType:
        type: "Time"
    - name: "Booking ID"
      dataType:
        type: "String"
    - name: "Booking Status"
      dataType:
        type: "String"
    - name: "Customer ID"
      dataType:
        type: "String"
    - name: "Vehicle Type"
      dataType:
        type: "String"
    - name: "Pickup Location"
      dataType:
        type: "String"
    - name: "Drop Location"
      dataType:
        type: "String"
    - name: "Avg VTAT"
      dataType:
        type: "String"
    - name: "Avg CTAT"
      dataType:
        type: "String"
    - name: "Cancelled Rides by Customer"
      dataType:
        type: "String"
    - name: "Reason for cancelling by Customer"
      dataType:
        type: "String"
    - name: "Cancelled Rides by Driver"
      dataType:
        type: "String"
    - name: "Driver Cancellation Reason"
      dataType:
        type: "String"
    - name: "Incomplete Rides"
      dataType:
        type: "String"
    - name: "Incomplete Rides Reason"
      dataType:
        type: "String"
    - name: "Booking Value"
      dataType:
        type: "String"
    - name: "Ride Distance"
      dataType:
        type: "String"
    - name: "Driver Ratings"
      dataType:
        type: "String"
    - name: "Customer Rating"
      dataType:
        type: "String"
    - name: "Payment Method"
      dataType:
        type: "String"
    type: "table"
